accounts/urls.py
from django.urls import path
from . import views

app_name='accounts'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('update/', views.update, name='update'),
    path('delete/', views.delete, name='delete'),
    path('password/', views.password_change, name='password_change'),
]

movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'
urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/update/', views.update, name='update'),
    path('<int:pk>/delete/', views.delete, name='delete'),
]

mypjt/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('movies/', include('movies.urls')),
    path('accounts/', include('accounts.urls')),
]

accounts/models.py
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    pass

movies/models.py
from django.db import models

# Create your models here.
class Movie(models.Model):
    title = models.CharField(max_length=20)
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth import get_user_model

class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = get_user_model()

class CustomUserChangeForm(UserChangeForm):
    class Meta(UserChangeForm.Meta):
        model = get_user_model()
        fields = ['first_name', 'last_name']

movies/forms.py
from django import forms
from .models import Movie

class MovieForm(forms.ModelForm):
    class Meta:
        model = Movie
        fields = '__all__'

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from django.contrib.auth import login as auth_login, logout as auth_logout
from .forms import CustomUserCreationForm, CustomUserChangeForm
from django.contrib.auth import update_session_auth_hash
from django.views.decorators.http import require_http_methods, require_safe, require_POST

@require_http_methods(['GET', 'POST'])
def login(request):
    if request.method == "POST":
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect("movies:index")
    else:
        form = AuthenticationForm()
    context = {
        'form':form
    }
    return render(request, "accounts/login.html", context)


@require_safe
def logout(request):
    auth_logout(request)
    return redirect("movies:index")


@require_http_methods(['GET', 'POST'])
def signup(request):
    if request.method == "POST":
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request, user)
            return redirect("movies:index")
    else:
        form = CustomUserCreationForm()
    context = {
        'form':form,
    }
    return render(request, "accounts/signup.html", context)


@require_http_methods(['GET', 'POST'])
def update(request):
    if request.method == "POST":
        form = CustomUserChangeForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect("movies:index")
    else:
        form = CustomUserChangeForm(instance=request.user)
    context = {
        'form':form,
    }
    return render(request, "accounts/update.html", context)


@require_http_methods(['GET', 'POST'])
def password_change(request):
    if request.method == "POST":
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect("movies:index")
    else:
        form = PasswordChangeForm(request.user)
    context = {
        'form':form,
    }
    return render(request, "accounts/password_change.html", context)


@require_safe
def delete(request):
    request.user.delete()
    auth_logout(request)
    return redirect("movies:index")

movies/views.py
from django.shortcuts import render, redirect
from .models import Movie
from .forms import MovieForm
from django.views.decorators.http import require_http_methods, require_safe, require_POST



# READ
@require_safe
def index(request):
    movies = Movie.objects.all()
    context = {
        'movies':movies,
        }
    return render(request, 'movies/index.html', context)


@require_safe
def detail(request, pk):
    movie = Movie.objects.get(pk=pk)
    context = {
        'movie': movie
        }
    return render(request, 'movies/detail.html', context)


# CREATE
@require_http_methods(['GET', 'POST'])
def create(request):
    if request.method == 'POST':
        form = MovieForm(request.POST)
        if form.is_valid():
            movie = form.save()
            return redirect('movies:detail', movie.pk)
    else:
        form = MovieForm()

    context = {
        'form': form
        }
    return render(request, 'movies/create.html', context)


# DELETE
@require_POST
def delete(request, pk):
    movie = Movie.objects.get(pk=pk)
    movie.delete()
    return redirect('movies:index')


# UPDATE
@require_http_methods(['GET', 'POST'])
def update(request, pk):
    movie = Movie.objects.get(pk=pk)

    if request.method == 'POST':
        form = MovieForm(request.POST, instance=movie)
        if form.is_valid():
            form.save()
            return redirect('movies:detail', pk=movie.pk)
    else:
        form = MovieForm(instance=movie)

    context = {
        'form': form, 
        'movie': movie
        }
    return render(request, 'movies/update.html', context)

accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block content %}
<h2 class="lh-lg"> Login </h2>
<form action="{% url 'accounts:login' %}" method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="login">
</form>
{% endblock content %}

accounts/templates/accounts/password_change.html
{% extends 'base.html' %}

{% block content %}
  <h2 class="lh-lg"> Password Change </h2>
  <form action="{% url 'accounts:password_change' %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="change password">
  </form>
{% endblock content %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}

{% block content %}
<h2 class="lh-lg"> Create Account</h2>
<form action="{% url 'accounts:signup' %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input class="btn btn-success" type="submit" value="signup">
</form>
{% endblock content %}

accounts/templates/accounts/update.html
{% extends 'base.html' %}

{% block content %}
  <h2 class="lh-lg"> Update </h2>
  <form action="{% url 'accounts:update' %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="update">
  </form>
{% endblock content %}

movies/templates/movies/create.html
{% extends 'base.html' %} 

{% block content %}
    <h1>CREATE</h1>
    <hr />

    <form action="{% url 'movies:create' %}" method="POST">
        {% csrf_token %} 
        {{form.as_p}}
        <input type="submit" value="작성하기"/>
    </form>

    <br />
    <hr>
    <a href="{% url 'movies:index' %}">목록보기</a>
{% endblock content %}

movies/templates/movies/detail.html
{% extends 'base.html' %} 

{% block content %}
  <h1>DETAIL</h1>
  <hr />


  <div id="movie-content">
    <p>{{movie.title}}</p>
    <p>{{movie.description}}</p>
    <p>생성시각 : {{movie.created_at}}</p>
    <p>수정시각 : {{movie.updated_at}}</p>

    <hr>
    <a href="{% url 'movies:update' movie.pk %}">수정하기</a>
    <form action="{% url 'movies:delete' movie.pk %}" method="POST">
      {% csrf_token %}
      <input type="submit" value="삭제하기"/>
    </form>
    <br>
    <hr>
    <a href="{% url 'movies:index' %}">목록보기</a>
  </div>
{% endblock content %}

movies/templates/movies/index.html
{% extends 'base.html' %}

{% block content %}
    <h1>index</h1>
    <a href="{% url 'movies:create' %}">[CREATE]</a>
    <hr>
    {% for movie in movies %}
        <a href="{% url 'movies:detail' movie.pk%}">
            {{ movie.title }}
        </a>
        <hr>
    {% endfor %}
{% endblock content %}

movies/templates/movies/update.html
{% extends 'base.html' %} 

{% block content %}
  <h1>UPDATE</h1>
  <hr />

  <form action="{% url 'movies:update' movie.pk %}" method="POST">
    {% csrf_token %} {{form.as_p}}
    <input type="submit" />
  </form>

  <hr />
  <a href="{% url 'movies:detail' movie.pk %}">돌아가기</a>
{% endblock content %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
  <title>Document</title>
</head>
<body>
  {% if user.is_authenticated %}
    <a href="{% url 'accounts:logout' %}">로긔아웃</a>
    <a href="{% url 'accounts:update' %}">정보수정하긔</a>
    <a href="{% url 'accounts:delete' %}">탈퇴하긔 ㅠ?</a>
  {% else %}
    <a href="{% url 'accounts:login' %}">로긘?</a>
    <a href="{% url 'accounts:signup' %}">[합류하기]</a>
  {% endif %}
  {% block content %}
  
  {% endblock content %}
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
</body>
</html>